#!/bin/bash
#
#PBS -N SNM_ModelFitting_rev5_EnsembleAggregation
#PBS -l select=1:ncpus=16:mem=16gb:interconnect=fdr
#PBS -l walltime=72:00:00

#PBS -m abe
#PBS -j oe

# ensure that /local_scratch is created on all nodes:
module load openmpi/3.1.6-gcc
mpirun sleep 20
module purge
module add matlab/2018b


# copy data from /home to /local_scratch
for node in `uniq $PBS_NODEFILE`
do
    ssh $node cp /home/jdroger/SNM_ModelFitting/scripts/* $TMPDIR
    cp /home/jdroger/SNM_ModelFitting/results/Ensemble/ga_*.mat $TMPDIR
done


# start job
cd $TMPDIR
taskset -c 0-$(($OMP_NUM_THREADS-1)) matlab -nodisplay -nosplash < EnsembleAggregation_training.m


# copy data from /local_scratch to /home
for node in `uniq $PBS_NODEFILE`
do
    ssh $node cp $TMPDIR/ga_aggregate_*.mat /home/jdroger/SNM_ModelFitting/results/Ensemble
    ssh $node cp $TMPDIR/ga_speciesNames.mat /home/jdroger/SNM_ModelFitting/results/Ensemble
done
